# Generated by Django 3.2.5 on 2021-07-18 19:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('award', '0002_project'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='project',
            options={'ordering': ['-pk']},
        ),
    ]
